# Generated by Django 2.1.7 on 2019-05-16 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='available_hours',
            field=models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(22), django.core.validators.MaxValueValidator(40)], verbose_name='Available Hours'),
        ),
    ]
