# Generated by Django 2.1.7 on 2019-03-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190317_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TC', 'Teacher'), ('CO', 'Coordinator'), ('AD', 'Admin')], max_length=15, verbose_name='User Type'),
        ),
    ]
