# Generated by Django 2.1.7 on 2019-05-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190501_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(blank=True, choices=[('Novicio', 'Novicio'), ('Docente', 'Docente'), ('Master', 'Master')], default='Novicio', max_length=15),
        ),
    ]
