# Generated by Django 2.1.7 on 2019-03-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0004_auto_20190320_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.Program'),
        ),
    ]
