# Generated by Django 2.1.7 on 2019-05-18 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190516_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='pcp',
            new_name='pdp',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='auto_eval',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Teacher Evaluation'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='available_hours',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Available Hours'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='coor_eval',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Coordinator Evaluation'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='observations',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student_eval',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Student Evaluation'),
        ),
    ]
