# Generated by Django 2.1.7 on 2019-03-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_coordinator_programa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='programa',
            new_name='program',
        ),
    ]
