# Generated by Django 2.1.7 on 2019-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20190327_1923'),
        ('accounts', '0006_auto_20190320_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='academics.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subprogramas',
            field=models.ManyToManyField(related_name='subprograms', to='academics.SubProgram'),
        ),
    ]
