# Generated by Django 2.1.7 on 2019-04-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190328_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='identification',
            field=models.BigIntegerField(unique=True),
        ),
    ]
