# Generated by Django 2.1.7 on 2019-04-01 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20190327_1923'),
        ('accounts', '0008_auto_20190401_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subprogramas',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subprograms',
            field=models.ManyToManyField(related_name='subprograms', to='academics.SubProgram', verbose_name='Sub-Programas'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='auto_eval',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Evaluación Profesor'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='coor_eval',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Evaluación Cordinador'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(blank=True, choices=[('NV', 'Novicio'), ('DC', 'Docente'), ('MA', 'Master')], default='NV', max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student_eval',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Evaluación Estudiante'),
        ),
    ]
