# Generated by Django 2.1.7 on 2019-03-21 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='intensity',
            field=models.CharField(choices=[('SM', 'Semestral'), ('RE', 'Regular'), ('SI', 'Semi-Intensivo'), ('IN', 'Intensivo'), ('UL', 'Ultra')], max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date (YYYY-MM-DD)'),
        ),
    ]
