# Generated by Django 2.1.7 on 2019-03-31 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20190327_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='intensity',
            field=models.CharField(choices=[('IN', 'Intensivo'), ('SI', 'Semi-Intensivo'), ('RE', 'Regular')], max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher'),
        ),
    ]
