# Generated by Django 2.1.7 on 2019-04-29 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='maxium_hours',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(40)], verbose_name='Maxium Hours'),
            preserve_default=False,
        ),
    ]
