# Generated by Django 2.1.7 on 2019-05-01 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher_maxium_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='maxium_hours',
        ),
        migrations.AddField(
            model_name='teacher',
            name='available_hours',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Available Hours'),
        ),
    ]
