# Generated by Django 2.1.7 on 2019-03-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academics.Program')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academics.SubProgram'),
        ),
    ]
