# Generated by Django 2.1.7 on 2019-04-29 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date (YYYY-MM-DD)'),
        ),
    ]
