# Generated by Django 2.1.7 on 2019-03-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_auto_20190321_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Program'),
        ),
    ]
