# Generated by Django 2.1.7 on 2019-05-15 21:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('intensity', models.CharField(choices=[('Intensivo', 'Intensivo'), ('Semi-Intensivo', 'Semi-Intensivo'), ('Regular', 'Regular')], max_length=15)),
                ('monday', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', ''), ('7', ''), ('8', ''), ('9', ''), ('10', ''), ('11', ''), ('12', ''), ('13', ''), ('14', ''), ('15', ''), ('16', ''), ('17', ''), ('18', ''), ('19', ''), ('20', '')], max_length=40, null=True)),
                ('tuesday', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', ''), ('7', ''), ('8', ''), ('9', ''), ('10', ''), ('11', ''), ('12', ''), ('13', ''), ('14', ''), ('15', ''), ('16', ''), ('17', ''), ('18', ''), ('19', ''), ('20', '')], max_length=40, null=True)),
                ('wednesday', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', ''), ('7', ''), ('8', ''), ('9', ''), ('10', ''), ('11', ''), ('12', ''), ('13', ''), ('14', ''), ('15', ''), ('16', ''), ('17', ''), ('18', ''), ('19', ''), ('20', '')], max_length=40, null=True)),
                ('thursday', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', ''), ('7', ''), ('8', ''), ('9', ''), ('10', ''), ('11', ''), ('12', ''), ('13', ''), ('14', ''), ('15', ''), ('16', ''), ('17', ''), ('18', ''), ('19', ''), ('20', '')], max_length=40, null=True)),
                ('friday', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', ''), ('7', ''), ('8', ''), ('9', ''), ('10', ''), ('11', ''), ('12', ''), ('13', ''), ('14', ''), ('15', ''), ('16', ''), ('17', ''), ('18', ''), ('19', ''), ('20', '')], max_length=40, null=True)),
                ('saturday', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', ''), ('7', ''), ('8', ''), ('9', ''), ('10', ''), ('11', ''), ('12', ''), ('13', ''), ('14', ''), ('15', ''), ('16', ''), ('17', ''), ('18', ''), ('19', ''), ('20', '')], max_length=40, null=True)),
            ],
        ),
    ]
