# Generated by Django 2.1.7 on 2019-05-16 02:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='friday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', '6:00 - 7:00'), ('7', '7:00 - 8:00'), ('8', '8:00 - 9:00'), ('9', '9:00 - 10:00'), ('10', '10:00 - 11:00'), ('11', '11:00 - 12:00'), ('12', '12:00 - 13:00'), ('13', '13:00 - 14:00'), ('14', '14:00 - 15:00'), ('15', '15:00 - 16:00'), ('16', '16:00 - 17:00'), ('17', '17:00 - 18:00'), ('18', '18:00 - 19:00'), ('19', '19:00 - 20:00'), ('20', '20:00 - 21:00')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', '6:00 - 7:00'), ('7', '7:00 - 8:00'), ('8', '8:00 - 9:00'), ('9', '9:00 - 10:00'), ('10', '10:00 - 11:00'), ('11', '11:00 - 12:00'), ('12', '12:00 - 13:00'), ('13', '13:00 - 14:00'), ('14', '14:00 - 15:00'), ('15', '15:00 - 16:00'), ('16', '16:00 - 17:00'), ('17', '17:00 - 18:00'), ('18', '18:00 - 19:00'), ('19', '19:00 - 20:00'), ('20', '20:00 - 21:00')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', '6:00 - 7:00'), ('7', '7:00 - 8:00'), ('8', '8:00 - 9:00'), ('9', '9:00 - 10:00'), ('10', '10:00 - 11:00'), ('11', '11:00 - 12:00'), ('12', '12:00 - 13:00'), ('13', '13:00 - 14:00'), ('14', '14:00 - 15:00'), ('15', '15:00 - 16:00'), ('16', '16:00 - 17:00'), ('17', '17:00 - 18:00'), ('18', '18:00 - 19:00'), ('19', '19:00 - 20:00'), ('20', '20:00 - 21:00')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', '6:00 - 7:00'), ('7', '7:00 - 8:00'), ('8', '8:00 - 9:00'), ('9', '9:00 - 10:00'), ('10', '10:00 - 11:00'), ('11', '11:00 - 12:00'), ('12', '12:00 - 13:00'), ('13', '13:00 - 14:00'), ('14', '14:00 - 15:00'), ('15', '15:00 - 16:00'), ('16', '16:00 - 17:00'), ('17', '17:00 - 18:00'), ('18', '18:00 - 19:00'), ('19', '19:00 - 20:00'), ('20', '20:00 - 21:00')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', '6:00 - 7:00'), ('7', '7:00 - 8:00'), ('8', '8:00 - 9:00'), ('9', '9:00 - 10:00'), ('10', '10:00 - 11:00'), ('11', '11:00 - 12:00'), ('12', '12:00 - 13:00'), ('13', '13:00 - 14:00'), ('14', '14:00 - 15:00'), ('15', '15:00 - 16:00'), ('16', '16:00 - 17:00'), ('17', '17:00 - 18:00'), ('18', '18:00 - 19:00'), ('19', '19:00 - 20:00'), ('20', '20:00 - 21:00')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6', '6:00 - 7:00'), ('7', '7:00 - 8:00'), ('8', '8:00 - 9:00'), ('9', '9:00 - 10:00'), ('10', '10:00 - 11:00'), ('11', '11:00 - 12:00'), ('12', '12:00 - 13:00'), ('13', '13:00 - 14:00'), ('14', '14:00 - 15:00'), ('15', '15:00 - 16:00'), ('16', '16:00 - 17:00'), ('17', '17:00 - 18:00'), ('18', '18:00 - 19:00'), ('19', '19:00 - 20:00'), ('20', '20:00 - 21:00')], max_length=40, null=True),
        ),
    ]
