# Generated by Django 2.1.7 on 2019-03-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='he', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
