# Generated by Django 2.1.7 on 2019-03-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='intensity',
            field=models.CharField(choices=[('IN', 'Intensivo'), ('SI', 'Semi-Intensivo'), ('RE', 'Regular')], default='d', max_length=15),
            preserve_default=False,
        ),
    ]
