# Generated by Django 2.1.7 on 2019-05-04 05:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20190503_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='friday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6to7', ''), ('7to8', ''), ('8to9', ''), ('9to10', ''), ('10to11', ''), ('11to12', ''), ('12to13', ''), ('13to14', ''), ('14to15', ''), ('15to16', ''), ('16to17', ''), ('17to18', ''), ('18to19', ''), ('19to20', ''), ('20to21', '')], max_length=97, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6to7', ''), ('7to8', ''), ('8to9', ''), ('9to10', ''), ('10to11', ''), ('11to12', ''), ('12to13', ''), ('13to14', ''), ('14to15', ''), ('15to16', ''), ('16to17', ''), ('17to18', ''), ('18to19', ''), ('19to20', ''), ('20to21', '')], max_length=97, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6to7', ''), ('7to8', ''), ('8to9', ''), ('9to10', ''), ('10to11', ''), ('11to12', ''), ('12to13', ''), ('13to14', ''), ('14to15', ''), ('15to16', ''), ('16to17', ''), ('17to18', ''), ('18to19', ''), ('19to20', ''), ('20to21', '')], max_length=97, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6to7', ''), ('7to8', ''), ('8to9', ''), ('9to10', ''), ('10to11', ''), ('11to12', ''), ('12to13', ''), ('13to14', ''), ('14to15', ''), ('15to16', ''), ('16to17', ''), ('17to18', ''), ('18to19', ''), ('19to20', ''), ('20to21', '')], max_length=97, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6to7', ''), ('7to8', ''), ('8to9', ''), ('9to10', ''), ('10to11', ''), ('11to12', ''), ('12to13', ''), ('13to14', ''), ('14to15', ''), ('15to16', ''), ('16to17', ''), ('17to18', ''), ('18to19', ''), ('19to20', ''), ('20to21', '')], max_length=97, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6to7', ''), ('7to8', ''), ('8to9', ''), ('9to10', ''), ('10to11', ''), ('11to12', ''), ('12to13', ''), ('13to14', ''), ('14to15', ''), ('15to16', ''), ('16to17', ''), ('17to18', ''), ('18to19', ''), ('19to20', ''), ('20to21', '')], max_length=97, null=True),
        ),
    ]
