# Generated by Django 2.1.7 on 2019-05-18 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190518_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='auto_eval',
        ),
        migrations.AddField(
            model_name='teacher',
            name='self_eval',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Self-Evaluation'),
        ),
    ]
