# Generated by Django 2.1.7 on 2019-05-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190518_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pdp',
            field=models.BooleanField(default=False, verbose_name='PDP'),
        ),
    ]
