# Generated by Django 2.1.7 on 2019-05-18 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190518_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='epik_unique_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Epik Unique Number'),
        ),
    ]
