# Generated by Django 2.1.7 on 2019-05-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='intensity',
            field=models.CharField(choices=[('Intensivo', 'Intensivo'), ('Semi-Intensivo', 'Semi-Intensivo'), ('Regular', 'Regular')], max_length=15),
        ),
    ]
